package me.xueyao.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.14
 * 2021-09-13T13:50:57.040+08:00
 * Generated source version: 3.2.14
 *
 */
@WebService(targetNamespace = "http://service.webservice.example.com", name = "ServerServiceDemo")
@XmlSeeAlso({ObjectFactory.class})
public interface ServerServiceDemo {

    @WebMethod
    @RequestWrapper(localName = "emrService", targetNamespace = "http://service.webservice.example.com", className = "me.xueyao.ws.EmrService")
    @ResponseWrapper(localName = "emrServiceResponse", targetNamespace = "http://service.webservice.example.com", className = "me.xueyao.ws.EmrServiceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String emrService(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
