
package me.xueyao.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.14
 * 2021-09-13T13:50:57+08:00
 * Generated source version: 3.2.14
 *
 */
public final class ServerServiceDemo_ServerServiceDemoPort_Client {

    private static final QName SERVICE_NAME = new QName("http://server.webservice.example.com", "ServerServiceDemoImplService");

    private ServerServiceDemo_ServerServiceDemoPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ServerServiceDemoImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ServerServiceDemoImplService ss = new ServerServiceDemoImplService(wsdlURL, SERVICE_NAME);
        ServerServiceDemo port = ss.getServerServiceDemoPort();

        {
        System.out.println("Invoking emrService...");
        java.lang.String _emrService_arg0 = "测试内容";
        java.lang.String _emrService__return = port.emrService(_emrService_arg0);
        System.out.println("emrService.result=" + _emrService__return);


        }

        System.exit(0);
    }

}
